gcp_project = "wise-key-423412-q8"
gcp_region = "europe-north1"
gcp_zone = "europe-north1a"
spalojoki_infra_bucket = "spalojoki-infrastructure-bucket"
terraform_service_account_email="spalojoki-infra-tf@wise-key-423412-q8.iam.gserviceaccount.com"