gcp_project = "spalojoki-infrastructure"
gcp_region = "europe-north1"
gcp_zone = "europe-north1a"
infra_bucket_name = "spalojoki-infra-bucket"
terraform_service_account_email="terraform-admin@spalojoki-infrastructure.iam.gserviceaccount.com"