- name: Ensure /srv/postgres directory exists
  file:
    path: /srv/postgres
    state: directory
    mode: '0755'

- name: Copy Postgres Docker Compose template
  template:
    src: docker-compose.yml.j2
    dest: /srv/postgres/docker-compose.yml
  become: yes

- name: Start postgres container
  command: docker compose up -d
  args:
    chdir: /srv/postgres