- hosts: analytics
  become: yes
  vars_files:
    - "{{ playbook_dir }}/../vars/analytics.yml"
  roles:
    - role: common
    - role: gcloud
      vars:
        gcloud_sa_path: "{{ playbook_dir }}/../files/sak.json"
    - role: postgres
    - role: watchtower
      vars:
        watchtower_config_path: "{{ playbook_dir }}/../files/watchtower_config.json"
    - role: airflow