- name: Ensure /srv/watchtower directory exists
  file:
    path: /srv/watchtower
    state: directory
    mode: '0755'

- name: Copy Watchtower docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /srv/watchtower/docker-compose.yml

- name: Copy service account key file
  copy:
    src: "{{ watchtower_config_path }}"
    dest: /srv/watchtower/config.json
    mode: '0600'

- name: Start Watchtower container
  command: docker compose up -d
  args:
    chdir: /srv/watchtower